Repository El-Duckster/EscapeRoom-grupp2, pull requests merged in 2024-11, with the labels that each got.

#24 Feature/api service
  index.html
  js/apiService.js
  js/apiTest.js
Labels: Moment 1

#36 challenges.html-Add primary elements for header, footer, section filter and Modal
  challenges.html
  index.html
  js/menu.js
  styles/layouts/css/main.css
  styles/layouts/css/main.css.map
  styles/layouts/css/rooms.css
  styles/layouts/css/rooms.css.map
  styles/layouts/scss/rooms.scss
Labels: good first issue

#43 Feature/filter challenges button
  challenges.html
  styles/layouts/css/filter.css
  styles/layouts/css/filter.css.map
  styles/layouts/css/main.css
  styles/layouts/css/main.css.map
  styles/layouts/scss/filter.scss
  styles/layouts/scss/main.scss
Labels: Moment 2

#62 Feature/filter modal structure
  challenges.html
  js/filteringBox.js
  styles/global-styles/_buttons.scss
  styles/layouts/css/filter.css
  styles/layouts/css/filter.css.map
  styles/layouts/css/main.css
  styles/layouts/css/main.css.map
  styles/layouts/css/rooms.css
  styles/layouts/css/rooms.css.map
  styles/layouts/scss/filter.scss
  styles/layouts/scss/header.scss
  styles/layouts/scss/rooms.scss
Labels: Moment 2

#65 Added search field for keywords, currently w/o function
  js/filteringBox.js
Labels: Moment 2

#64 Added checkbox filters for challenges type, currently w/o function
  js/filteringBox.js
Labels: Moment 2

#66 Enhance filtering box with tag-based filtering and improved search functionality
  js/filteringBox.js
Labels: Moment 2

#71 Install Vite and Configure Project for SCSS Compilation
  .gitignore
  package-lock.json
  package.json
  styles/layouts/css/footer.css
  styles/layouts/css/footer.css.map
  styles/layouts/css/header.css
  styles/layouts/css/header.css.map
  styles/layouts/css/online-onsite-btns.css
  styles/layouts/css/online-onsite-btns.css.map
  styles/layouts/css/page1.css.map
  styles/layouts/css/page2.css.map
  styles/layouts/css/play.css
  styles/layouts/css/play.css.map
  styles/layouts/css/story.css
  styles/layouts/css/story.css.map
  styles/layouts/css/style.css.map
  styles/layouts/css/testimoials.css.map
  styles/layouts/css/testimonials.css
  styles/layouts/css/testimonials.css.map
  styles/layouts/scss/main.scss
  styles/layouts/scss/modal.scss
  vite.config.js
Labels: enhancement

#59 add features to Modul booking -step 2
  challenges.html
  index.html
  js/apiService.js
  js/apiTest.js
  js/modul-step-2.js
  styles/layouts/css/module-step-2.css
  styles/layouts/css/module-step-2.css.map
  styles/layouts/scss/main.scss
  styles/layouts/scss/module-step-2.scss
Labels: Moment 3

#77 Feature/add button labels and renderChallenges
  challenges.html
  index.html
  js/challengeClass.js
  js/displayAllChallenges.js
  js/displayMainPageChallenges.js
  js/filteringBox.js
  js/utilities/renderChallenges.js
  package-lock.json
  package.json
  styles/global-styles/_carousel.scss
  styles/layouts/scss/rooms.scss
Labels: Moment 1

#80 Dynamic tags, searchfield & checkboxes styling.
  src/js/filteringBox.js
  src/styles/layouts/filter.scss
Labels: Moment 2

#84 Filter rating stars
  src/js/filteringBox.js
  src/styles/layouts/filter.scss
Labels: Moment 2

#86 Online/on-site buttons on index leading to filtered challenges
  index.html
  src/js/filteringBox.js
  src/js/menu.js
Labels: Moment 2
